debug: false
# actuator endpoint all active
management.endpoints.web.exposure.include: "*"

# log level 구체적으로 명시
logging:
  level:
    com.example.hellpyending: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # ? -> Binding Parameter 관찰 가능(개발 단계)

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hellpyending
    username: test
    password: test1234!@#$
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # 초기 데이터를 생성하겧 할 수 있다. -> data.sql(약속)
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # N + 1 문제 해결 bulk query
  sql.init.mode: always   # data.sql 언제 작동 시킬것인가? ALWAYS, NEVER, EMBEDDED(임베디드 디비로 사용될 때만: TEST)
  #  thymeleaf.cache: false
  #  data:
  #    rest:
  #      base-path: /api
  #      detection-strategy: annotated
  # h2.console.enabled: true
  output:
    ansi:
      enabled: always


---
# 특정 profile yaml 파일 시작
